image: python:3.9

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

cache:
  paths:
    - .pip-cache/

before_script:
  - pip install -r backend/requirements.txt

test:
  stage: test
  script:
    - cd backend
    - python manage.py test
    - flake8 .

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - cd backend
    - dpl --provider=heroku --app=your-heroku-app-name --api-key=$HEROKU_API_KEY
  only:
    - main