name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run tests
      run: |
        cd backend
        python manage.py test
    - name: Run linter
      run: |
        pip install flake8
        cd backend
        flake8 .

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: "your-heroku-app-name"
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        git subtree push --prefix backend https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git main